### ISSUE TITLE
WP-CLI and Deployment Workflow

### ISSUE THREAD

**Issue by jeffkamo** [Hoshu-Dojo/hoshudojo.com#1]
## Links
- http://www.jeffshaikh.com/wordpress-workflow/
- http://demental.info/blog/2013/04/09/a-decent-wordpress-deploy-workflow/
- https://github.com/demental/wp-deploy-flow
- https://www.npmjs.com/package/grunt-wp-plugins
## Todo
- [x] Install and get WP-CLI working on local
  - [ ] Convert WP-CLI implementation to be an npm module
  - [ ] and a grunt task
- [x] On remote too?
  - [x] #2 Prepare a Wordpress installation on stage
- [ ] Test run WP-CLI and the wp-deploy-flow from Local to a staging server so they work together
